# Generated by Django 2.2.8 on 2020-09-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='slate_id',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
