# Generated by Django 2.2 on 2020-09-11 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_friend_slate_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='lives_in',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='nick_name',
        ),
    ]
