# Generated by Django 2.2 on 2020-09-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20200911_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='exam',
            field=models.TextField(default=''),
        ),
    ]
