# Generated by Django 2.2 on 2020-09-13 00:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_friend_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
