# Generated by Django 2.2.8 on 2020-09-15 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_friend_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='created',
        ),
    ]
