# Generated by Django 3.1.1 on 2020-09-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_auto_20200915_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='exam',
            field=models.JSONField(default='[]'),
        ),
    ]
