# Generated by Django 3.1.1 on 2020-09-18 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_friend_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='grade',
        ),
    ]
