# Generated by Django 3.1.1 on 2020-09-18 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_auto_20200918_0401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='next_question',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='previous_question',
        ),
    ]
